### ISSUE TITLE
Module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by intheweeds** [twitter/communitynotes#111]
**Describe the bug**
I attempted to run sourcecode/main.py and received the following error:

`
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?
`

If I replace instances of 'np.object' with 'object', the error is resolved, but I also have to do the same with 'np.str' and 'np.float'.

This is a Windows environment. Is there a suggested environment? I did not see any in the documentation.

I saw this was referenced in issue #87, so I also tried to run on Ubuntu 22.04.2 LTS (via WSL2) and received the same error. The comments on the issue said the Python script was meant to run in *nix environments, but it's not clear which.

**To Reproduce**
1. With data files present in the 'sourcecode' folder and command prompt at the same folder, run:
`python .\main.py --enrollment .\userEnrollment-00000.tsv --notes .\notes-00000.tsv --ratings .\ratings-00000.tsv --status .\noteStatusHistory-00000.tsv --outdir scored_notes.tsv`
2. Observe output for errors.

**Expected behavior**
The script should execute without error.

**Environment**
Windows 11 Pro (22621.1702)
Python 3.11.3
numpy 1.24.3

Also:
Ubuntu 22.04.2 LTS (via WSL2)
Python 3.10.6
numpy 1.24.3

**Comment by chriskd** [comment]
I've also had the same error and fixed it the same way. My guess is that they're using a numpy version < 1.20 in production.

Have you tried installing numpy 1.19? You can do so with

`pip install numpy==1.19`

I'm not sure that'll fix the problem, but may be worth a try. I originally hoped to just install numpy 1.19 instead of having to patch the deprecated calls, but numpy 1.19 doesn't build on ARM Macs.

**Comment by intheweeds** [comment]
I attempted to do install numpy 1.19, as you suggested, but the build dependencies failed during pip install on both Windows and my Ubuntu installation. We're going back 2 years there and 1.20 was apparently a major update, so I'm not surprised.

It looks like it would be best to just update the code to work with latest versions. I'd be willing to try, but I've never contributed to an open source project, so I'd have to do some reading first. I'd also need to know the target environment currently used so I could test that my changes (which seem rather minor to me) don't break anything on the target *nix system.

**Comment by jbaxter** [comment]
Sorry for the trouble. Indeed we are using numpy==1.19.2. We ought to release a requirements.txt file to avoid this pain.

**Comment by intheweeds** [comment]
Thanks, that helps. Could you possibly provide a `pip list` with the versions of the dependencies? Specifically:
numpy (1.19.2)
pandas
matplotlib
torch

**Comment by elvey** [comment]
Are you having success running it now, @intheweeds ?   

I see above that 'numpy 1.19 doesn't build on ARM Macs' and I'm on an ARM Mac, so I can't run the code on one?  I tried and failed.   Could help troubleshoot the two bugs I've opened.

**Comment by jbaxter** [comment]
Thank you! Please reopen this if my fix doesn't resolve this for you.

**Comment by elvey** [comment]
Failure ... and success! 

FYI, this commit did not help:

https://github.com/twitter/communitynotes/commit/0191c30410e217f5a02fa7c3f58b60a1bceea98d

It  (the virtual environment) resulted in the errors below* when I tried `pip install -r requirements.txt`.

On the other hand, **I did have success**, after:

1. Updating my source with `git pull origin main` _So I presume your changes to support the curent version of numpy did fix the problem I was having.  Thank you!_
2. Adding `export PATH="/opt/homebrew/opt/python@3.11/libexec/bin:$PATH"` to my .zshrc, per https://apple.stackexchange.com/a/450306/33389, 
3. running `brew update`
4. giving up on the virtual environment
5. Optimistically installing the **default** (latest) versions of pandas, matplotlib and torch.
6. Running `python3 ../main.py` from .../communitynotes/sourcecode/data worked on data files from May.



*errors (also posted to the commit):
```(communitynotes_env) [....] communitynotes % pip install -r requirements.txt
Collecting numpy==1.19.2 (from -r requirements.txt (line 1))
  Downloading numpy-1.19.2.zip (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 9.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      warning: _philox.pyx:19:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
      Processing numpy/random/_bounded_integers.pxd.in
[...]
```

**Comment by elvey** [comment]
Doh!  Of course my attempt to use the venv didn't work - it was still trying to install numpy 1.19, which isn't possible on M1.
