### ISSUE TITLE
introduce community notes on user account

### ISSUE THREAD

**Issue by laplasz** [twitter/communitynotes#114]
**Is your feature request related to a problem? Please describe.**
Community notes is a very useful feature and now it is extended on media context - would be nice to somehow be extended on user accounts as well.
lots of twitter account created for a purpose of spread misleading information. Those accounts own several community notes on their tweets. The problem is that these accounts can create new tweets without indicating to readers that this account became controversial.

**Describe the solution you'd like**
Would be nice to highlight for readers that this account has many community noted tweets.

**Describe alternatives you've considered**
- Restrict reachability if an account reaches a certain level of community noted tweets
- show a label on user account like a number which would reflect on the number of community noted tweets
- give a community notes label to user account by enabling community notes on user account (not just on tweets) - so if a user account would get a community note then label the account with a visible sign for every tweets the user creates.

**Comment by Warrobot10** [comment]
The problem is, this is censorship. I think the feature adding if a account has been noted a significant amount of times would be helpful, but censoring these accounts would not be what twitter is aiming for.

**Comment by elvey** [comment]
I believe Twitter still has virality blacklists and such, [Warrobot10](https://github.com/Warrobot10). (“Trends Blacklist”, “Search Blacklist”, “Do Not Amplify”).  (Perhaps the names and buckets have changed a bit, perhaps not.) Freedom of speech without freedom of reach, as Elon put it.  
Twitter didn't go and unlock accounts that were locked for tweets that only violated the old content guidelines.

**Comment by jbaxter** [comment]
Thanks! Going to close for now to clean up old issues.
