### ISSUE TITLE
introduce community notes on video stream

### ISSUE THREAD

**Issue by laplasz** [twitter/communitynotes#116]
**Is your feature request related to a problem? Please describe.**
The problem is that although media content now can get community notes but that is probably works well only on pictures. Video can contain many statements which needs separated notes on those. 

**Describe the solution you'd like**
https://twitter.com/kcoleman/status/1671146865360814080?s=20
Could plausibly have notes attached to a transcript & associated with specific timestamps. Would not appear in the first livestream (takes non-zero time to get rating consensus) but most views happen async/later.

**Describe alternatives you've considered**

**Additional context**

**Comment by lucasnantonio** [comment]
Thanks for this suggestion, @laplasz! 
We're currently working on supporting notes on videos (like we do images), and we're really interested in the solution space you're pointing to: notes on specific timestamps or claims made in a video.

I'll close this issue now as there's no immediate action we can take, except keep delivering on our roadmap towards that goal. 

Thank you!
