### ISSUE TITLE
It is impossible to increase to 5 from 13

### ISSUE THREAD

**Issue by earthengine** [twitter/communitynotes#117]
**Describe the bug**
When the writing impact was decreased and the ability to write notes are restricted, sometimes it will end up in the profile "Unlock your ability to write" section showing an message like

```text
Increase your Rating Impact to 5, from your current score of 13.
```
This message makes no sense since you can't increase a big number to a smaller one.

**To Reproduce**
1. Rating notes so the Rating Impact is high enough (13 in this case).
2. Writing notes but get disapproved so the writing impact is negative .
3. Up to a certain point, the writing ability will be restricted (3 out of 5 notes rated unhelpful).
4. Go to profile, check the section mentioned above.

**Expected behavior**
A clear, accelerate, and achievable advice to unlock the writing ability.

**Screenshots**
![image](https://github.com/twitter/communitynotes/assets/2227031/4f11376e-98d5-4897-bf73-6843d18f3558)

**Environment**
Twitter Web on Windows 11, date is 22/06/2023

**Comment by earthengine** [comment]
Update: 24/06/2023 the message was updated to 

```test
Increase your Rating Impact to 18, from your current score of 13
```

This is the proper fix. Close issue.

**Comment by elvey** [comment]
I'm confused by this.  What is the current formula/calculation to determine whether to restrict note writing ability?  Is it documented?  (Do you happen to know, @earthengine ?)
