### ISSUE TITLE
communitynotes infrastructure is failing to remove misinformation from communitynotes even when reported.

### ISSUE THREAD

**Issue by elvey** [twitter/communitynotes#121]
The infrastructure algorithm seems to have the wrong amount of trust in people; communitynotes is failing on a note **with 4.8M Views** with demonstrably false health re. a public health emergency, violating https://help.twitter.com/en/rules-and-policies/crisis-misinformation (the violated policy). It's failing on note https://twitter.com/i/birdwatch/n/1648714744034123776 based on direct, 100% definitive factual, web-based evidence, despite multiple Reports.

I reported this via https://help.twitter.com/en/forms/community-note?note_id=1648714744034123776, as well as by sending a DM to @CommunityNotes, marked "URGENT!" and tweeting to @CommunityNotes:

 FALSE INFO IN YOUR NOTE: "The bivalent Pfizer vaccine is still approved by the FDA."

 NO!

 The *BIVALENT* is ONLY *AUTHORIZED under EUA*.

 It IS *NOT* FDA APPROVED!!! ONLY MONOVALENT IS/WAS!  "APPROVED" is NOT CORRECT!…".
**To Reproduce**
1. Go to https://twitter.com/sneako/status/1648696595439927305
2. Scroll down to the second (globally visible) community note.
3. See "The bivalent Pfizer vaccine is still approved by the FDA." at the end of the note.
4. Go to https://help.twitter.com/en/rules-and-policies/crisis-misinformation
5. See "advance a claim of fact, expressed in definitive terms;
be demonstrably false or misleading, based on widely available, authoritative sources; and
be likely to impact public safety or cause serious harm."
6. Go to https://eua.modernatx.com/recipients .
7. See "Moderna COVID-19 Vaccine, Bivalent has not been approved or licensed by the FDA"
8. Go to https://www.pfizer.com/products/product-detail/pfizer-biontech-covid-19-vaccine .
9. See "Pfizer-BioNTech COVID-19 Vaccine, Bivalent has not been approved or licensed by FDA"
10.  (_optional_) Rate note for
- **Sources do not support note** (Doesn't say it's approved; the word "approved" does not even appear in the source.)
- **Incorrect information**: FALSE: "The bivalent Pfizer vaccine is still approved by the FDA."
- **Typos or unclear language** ("monovalant")
- **Misses key points or irrelevant** (Misses distinction between FDA approved and FDA EUA'd.) 
- **Other** (There's no debate over whether "The bivalent Pfizer vaccine is still approved by the FDA." No one disputes it.  It's readily verifiable to 100% certainty that it's false.) 
11. (_optional_) DM @CommunityNotes, tweet to @CommunityNotes and @TwitterSafety about it. 
12. Report (# 0322519944.  
13. Get told "we didn’t find a violation of [our rules](https://help.twitter.com/rules-and-policies/twitter-rules). " 
14. Re-report. # 0328844553.  Ditto, and ditto with # 0320612475 (May 8) and # 0317707377 (April 20) too. 

**Expected behavior** 

1. Reports of @community notes with of false info in violation of policy should be actioned.  Algorithm should be tweaked so that action will be taken if this note is reported yet again.  
2. I've noticed that some @CommunityNotes accounts seem to be (based on volume) role accounts run by paid writers.  Twitter/the algorithm should detect and Twitter should investigate.  Money should not define truth of @CommunityNotes. 

Informed consent requires those vaccinated be aware if an injection is FDA approved or FDA EUA'd, to balance benefits and risks, especially as there are fully tested FDA-approved preventatives.

**Comment by elvey** [comment]
See also: Note ID 1656868930898784256.

**Comment by elvey** [comment]
Anything I can clarify?  Anyone? -elvey

**Comment by twitterbirdwatch** [comment]
Thank you for trying to help ensure notes are accurate — it is obviously critical to the product being valuable to people. The scoring algorithm takes a number of steps to try to reduce the likelihood of information that people believe is inaccurate appearing, for example bridging-based ranking and [tag outlier filtering](https://github.com/twitter/communitynotes/blob/main/documentation/under-the-hood/ranking-notes.md). We are regularly working to improve this further, e.g. with recent tag outlier filtering updates.

Additionally, it is worth keeping in mind that there may be cases where readers might overlook a specific word in a note because the note makes a larger point that they find informative regarding the contents of the post/tweet.

**Comment by elvey** [comment]
Please see steps 12, 13, and 14, above.  Marking this as completed was inappropriate.  I hear you about readers overlooking the issue.  Fair point.  But there was a clear violation of twitter rules that put lives at risk and may have killed people that X mis-handled repeatedly at step 13.  (If the data on safety is to be believed.)  In any case, the booster [was partly FDA-approved on September 11](https://floridahealthcovid19.gov/wp-content/uploads/2023/09/20230913-booster-guidance-final.pdf) (last week) despite safety issues noted in the government health official guidance at this link.

**Comment by elvey** [comment]
Would a SpaceX engineer mark an issue like this "closed" or "completed" knowing it would cause a safety issue again if left unaddressed?  Certainly not.  Yes, _readers_ might overlook a specific word.  But the record shows **twitter staff**, _four times in a row_, mismarked demonstrably false health re. **a public health emergency**, demonstrably violating https://help.twitter.com/en/rules-and-policies/crisis-misinformation (the violated policy) as not violative of [our rules](https://help.twitter.com/rules-and-policies/twitter-rules)." Surely, @elonmusk would not be ok with this. (I presume that account is not The Elon Musk, sadly.)
The problem is "communitynotes infrastructure is failing to remove misinformation from communitynotes even when reported," and that a particular piece of misinformation was mismarked 4 times in a row and not removed despite it being demonstrably false health re. a public health emergency demonstrably violating https://help.twitter.com/en/rules-and-policies/crisis-misinformation (the violated policy) is a _symptom_ of the issue.
