### ISSUE TITLE
I recently started being shown Community Notes in Spanish when connecting from a Mexican IP with no obvious way to see the English version, though my phone's language is English and I prefer English notes.

### ISSUE THREAD

**Issue by beej** [twitter/communitynotes#139]
It would be a better UX to default to showing notes in the language of the device and even better to allow the user to select their preference order for notes and best to expose notes in all available languages to the user.

**Comment by beej** [comment]
The title was meant to be part of the comment.  I tried to fix it and change the title to "Notes Language Selection", b it don't have the bits to even edit my comment, let alone the title.

So restrictive the settings here!

**Comment by lucasnantonio** [comment]
Hi @beej, thanks for reporting this case.
Could you share with us what languages you have selected on this screen?

https://twitter.com/i/flow/language_selector

**Comment by beej** [comment]
<img width="612" alt="Screen Shot 2023-08-18 at 12 26 46" src="https://github.com/twitter/communitynotes/assets/107385/e540ef46-d8bf-4245-b70c-cf7a3e37edde">

**Comment by lucasnantonio** [comment]
Thank you!

If you uncheck Spanish on that screen, it should (after a delay) stop showing Community Notes in Spanish for you. 
But that setting controls your entire experience on the platform, so you would see less Spanish content in general.

Is that ok, or are you looking for a way to filter Spanish content only from Community Notes?

**Comment by beej** [comment]
Thanks.  That's helpful, but I think the system should default to showing Community Notes in the user's preferred language when available.

Don't you?

The post I noticed this on has Community Notes in at least English and Spanish as I'd previously been shown the note in English, presumably before the Spanish note had been published.

**Comment by beej** [comment]
To be clear, I'm not looking to filter anything.  I'm looking for users to have control over which language note is shown when multiple notes are available.

**Comment by lucasnantonio** [comment]
Thanks beej. 

That language setting screen is the app's main way to know which languages you prefer. And it looks like you selected Spanish at some point while using it.

We use that setting to determine which notes we show you in the Community Notes timelines, as well as which notes are sent to your notifications asking for ratings.

There is one case we don't yet solve for: If a specific Tweet has multiple notes rated as Helpful, and they are in different languages, we show them randomly. This is an edge case we didn't anticipate and will be fixing soon. We'll show the note based on the settings selected above.

Let me know if there's anything else we're missing.

**Comment by beej** [comment]
Great!

Nope, you're not missing anything.

Will this issue be used to track the code changes?

**Comment by lucasnantonio** [comment]
We're not using this repo to track all projects and changes to the product. 
But we've discussed the edge case I mentioned and have added it to our (long!) list of things we need to get done.

I will close this for now, as it seems like we know what is happening and have a path to resolution. 
Thank you and let us know if anything else comes up, we can always re-open this issue.
