### ISSUE TITLE
Missing unit tests

### ISSUE THREAD

**Issue by brettwooldridge** [twitter/communitynotes#168]
**Describe the bug**
Elon told me to open this issue. Where are the unit tests to verify that results are as expected? They would be extremely useful, especially after refactors like the recent weighting adjustments.

**Expected behavior**
There should be unit tests to guard against regressions and document, in code, expected behaviors.

**Comment by jbaxter** [comment]
We have not open sourced the testing or evaluation code for now, sorry.
