### ISSUE TITLE
Hydrating community notes?

### ISSUE THREAD

**Issue by tsor13** [twitter/communitynotes#169]
I'd like to hydrate community notes based on `noteId`, just like you can hydrate tweets with their `tweetId`. However, I'm unable to find a way to do this with the twitter API, and it looks like the actual content of the community note is not present in the released data.

**How can I get the body of the actual community note?**

Here is the [X/Twitter API v2](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference) endpoint for a tweet: `https://api.twitter.com/2/tweets/{tweetId}`. However, it does not work when I put in a `noteId`.

Additionally, I see that the url `twitter.com/i/birdwatch/n/{nodeId}` goes to the community note, but does not seem (as far as I'm aware) to be accessible to the API.

**Comment by jbaxter** [comment]
Thanks for using the data! Currently the best way to get the body of Community Notes is in the summary field in the downloadable TSV https://twitter.com/i/communitynotes/download-data. There is no regular API support currently.

**Comment by tsor13** [comment]
@jbaxter  thank you for the reply! However, it looks like the summary is not even a summary of the community note, but rather a response to the prompt “Please explain the evidence behind your choices, to help others who see this tweet understand why it is not misleading” (https://communitynotes.twitter.com/guide/en/under-the-hood/download-data).

**Would it be possible to either a) add the body of the community notes to the data to download or b) add a way to hydrate it using the X/Twitter API?** Without either, it's impossible to do many analyses about the bodies of the community notes that are accepted over the ones that are rejected
