### ISSUE TITLE
Link leads to not found page

### ISSUE THREAD

**Issue by rothexD** [twitter/communitynotes#182]
**Describe the bug**
Clicking on a link leads to a not found page :( 

**To Reproduce**
1. Go to https://communitynotes.twitter.com/guide/de/about/introduction
2. Go to section
![image](https://github.com/twitter/communitynotes/assets/56934789/f66b1f00-a06b-441c-af68-6cc359cb74ea)
3. Click link
4. Land on not found page 
https://communitynotes.twitter.com/guide/en/about/under-the-hood/download-data
![image](https://github.com/twitter/communitynotes/assets/56934789/3e688e5c-6b01-4a9e-ab9a-ac7ecb500bd5)

**Expected behavior**
A page should be found.

**additional stuff**
on the english version of the page the link redirects to a valid page :)
https://communitynotes.twitter.com/guide/en/about/introduction#/about/introduction
![image](https://github.com/twitter/communitynotes/assets/56934789/b812f19f-dd03-42a9-84af-d5e2a3daeb23)

**Environment**
Chrome Version 120.0.6099.71, German Language Culture

**Comment by avalanchesiqi** [comment]
> 4. Land on not found page
> https://communitynotes.twitter.com/guide/en/about/under-the-hood/download-data

The correct link should be https://communitynotes.twitter.com/guide/en/under-the-hood/download-data (removing the `about` in the middle)

Not sure if communitynotes has a German version of data download page.

**Comment by lucasnantonio** [comment]
The link is now fixed. 
@avalanchesiqi is right, we don't have translations for the technical parts of the docs ("under the hood" section), but still, there was indeed a bug with the link.

Thanks for reporting!
