### ISSUE TITLE
Mobile app (iPad) reports "Your account may not be allowed to perform this action" on Submit

### ISSUE THREAD

**Issue by armchairancap** [twitter/communitynotes#188]
**Describe the bug**

Some time ago I got a notification I can write community notes. 
Today I tried to write a simple note (one paragraph note + one paragraph "Source: LINK") and was told I may not be allowed to perform this action. 

**To Reproduce**

1. Click on "Write a Community Note
2. Write a single-paragraph note followed by another paragraph ("Source: https://wikipedia.org/bla/blah")
3. Check "Yes" ("Did you link to sources...")
4. Click "Submit"

**Expected behavior**

Note gets submitted. Or, if I am not allowed to write community notes, don't let me see that "Write a Community Note" in post drop down menu.

**Screenshots**

![image](https://github.com/twitter/communitynotes/assets/127013963/f6dc9724-0a82-43c8-a62a-30e2dfe83885)

**Environment**

- X for iPadOS v10.21.2
- iPadOS 16.7.4

**Comment by armchairancap** [comment]
I later realized - I get that on desktop (Firefox) as well, so it seems it's consistent across different clients.

**Comment by tactipus** [comment]
Do you know how to use Postman?

**Comment by armchairancap** [comment]
Yes

**Comment by armchairancap** [comment]
Today my X for iOS prompted me to pick a CN rater nickname which I did and got notified both in there and on desktop that I can start rating CNs. 

![image](https://github.com/twitter/communitynotes/assets/127013963/314ca9a6-a3dc-4e98-be69-4ec3d033da11)

As you can see on this screenshot, I do not have the ability to write notes (yet), so at least now I know.

`Write a Community Note` still appears in post drop down menu (the same as before), but at least after this latest update if you're not qualified there's a prompt that immediately notifies you that at this time you can only rate, and not write, notes and you can avoid wasting time on composing a CN that can't be submitted. 
So, I think it's okay to close this issue now.
