### ISSUE TITLE
Cannot write notes while Impact Score is >5

### ISSUE THREAD

**Issue by cubedmeatgoeshere** [twitter/communitynotes#194]
**Describe the bug**
Cannot write notes while Impact Score is >5. See screenshots of profile scores

**To Reproduce**
1. Be a new CN user with Impact Score == 7
2. Attempt to write a note

**Environment**
Chrome 121.0.6167.86 and Firefox 122.0 

![firefox_Your_profile__X_—_Mozilla_Firefox_aYJ4ae0IkN](https://github.com/twitter/communitynotes/assets/96257138/5fb954bb-0e93-4937-ae6a-95478be2bc79)
![firefox_Your_profile__X_—_Mozilla_Firefox_PkgHJz66gl](https://github.com/twitter/communitynotes/assets/96257138/c27602d9-9a40-4546-9835-74e9d03cbf2b)

**Comment by jbaxter** [comment]
Thanks! It'd help us debug this if you were willing to privately share your X handle or community notes alias of the affected user with us over DM, but no need to if you don't want to.

**Comment by cubedmeatgoeshere** [comment]
It seems the issue resolved itself after (according to notification count of each Impact +1) achieving a 9 Impact Rating. 

I have sent a DM to X user @CommunityNotes with the affected user alias and with this issue ID.

**Comment by jbaxter** [comment]
Thanks! Will look into it but will resolve this Github issue given that it resolved for now.
