### ISSUE TITLE
The page asks to join again to an already existing user

### ISSUE THREAD

**Issue by SWhitefox** [twitter/communitynotes#202]
Found a problem with the Community notes account. The account exists, it is shown as mine, the ratings and notes written are visible, but accesing the settings results in an error. Notes can still be rated. Shortcuts to my account are missing. And the page asks to joing the community notes again.

1. Click the button to rate a note, shortcuts to the related CN account are missing. The page suggests to join instead.
2. Accesing the account from a link, everything seems OK but the settings page returns an error "this page doesn't exist".

Firefox/Android 13, web version

![Screenshot_2024-02-24-02-25-09-916_org mozilla firefox-edit](https://github.com/twitter/communitynotes/assets/97804310/36863c7a-ee53-4962-ad39-12970a9bb611)
![IMG_20240224_022605](https://github.com/twitter/communitynotes/assets/97804310/3686efe4-d3ef-42d2-b449-683e10e97d14)

**Comment by twitterbirdwatch** [comment]
Thank you for the report. Two questions:

1. What are you clicking on to get to the page shown in the second screenshot?

2. What do you see if you go to https://twitter.com/i/communitynotes/u/me ?

**Comment by SWhitefox** [comment]
1. The top right gear icon from my community notes profile, accessed from a previous note I had made.
2. My CM profile.

It seems that it was a temporary issue, everything is now back to normal.
