### ISSUE TITLE
X Premium to send messages issue

### ISSUE THREAD

**Issue by alieldeba** [twitter/communitynotes#215]
**Description**
I sent a message to a person in a while and then when I try to access this chat now the subscription to X Premium dialogue pops out and when I click on close it closes and shows again and again and I have to restart the app to get out of this.

**To Reproduce**
1. You should have DM someone before a year or something
2. Click on the double-up arrow icon on the messages tab in the bottom right
3. click on the chat that you DM a year ago
4. you now will see that the dialogue appears and you are stuck

**Expected behavior**

**Screenshots**
![image](https://github.com/twitter/communitynotes/assets/88302640/c989a967-c71a-474c-a2e6-6ca1154ad896)

**Environment**
Windows 11, Edge latest version

**Comment by alieldeba** [comment]
Here is a photo that I took in the delay before the dialogue appears

![Uploading image.png…]()

**Comment by jbaxter** [comment]
Thanks for the report, but this repo is for the open source Community Notes code only. Will go ahead and close this.

**Comment by alieldeba** [comment]
Then were to open this issue @jbaxter ?

**Comment by y7aa** [comment]
[``](**

> url

**)
