### ISSUE TITLE
Manager Bussines

### ISSUE THREAD

**Issue by Annie602942** [twitter/communitynotes#236]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by Annie602942** [comment]
Manager bussines verified my accoutn

**Comment by Annie602942** [comment]
2024-06-28T18:28:12.6230565Z Cleaning up orphan processes

**Comment by Kristinmikulski** [comment]
not sure what i do next


Thank You,
Kristin Mikulski
***@***.***
835-204-6854

The lust for power is not rooted in strength, but in weakness.
                                        -Erich Fromm
Sent with Spark
