### ISSUE TITLE
Community notes data is again out of date – most recent contribution was 7 days ago

### ISSUE THREAD

**Issue by andylolz** [twitter/communitynotes#259]
A similar issue occurred not very long ago – I flagged it in #254.

It looks like it is happening again – the note on https://x.com/i/communitynotes/download-data currently says:

> Data includes contributions up until 2:03 AM · Aug 18, 2024

I.e. 7 days ago.

It’s still useful to have these bulk data downloads even with this delay, but it would be useful to know if this length of delay should be expected going forward.

**Comment by andylolz** [comment]
Retrospectively closing this, as it was resolved.

There does seem to be a general problem, though, that community notes data always lags by more than the documented one day, and sometimes by significantly more.

**Comment by plopnl** [comment]
it's been down again for the last 5 or so days.
stuck on 1437535 notes

**Comment by andylolz** [comment]
Thanks, @plopnl – I’ve reopened this issue accordingly.

**Comment by andylolz** [comment]
In fact, I’ll close this (because it was resolved at the time) and will open a new issue.
