### ISSUE TITLE
Retrieving the User Who Posted a Tweet Using Only the Tweet ID

### ISSUE THREAD

**Issue by Liumucan** [twitter/communitynotes#262]
Recently, I've been interested in analyzing the Community Notes data. When I tried to analyze the Notes table, I found that it only contains the tweetId without the ID of the user who posted the note. While I can search for the ID to retrieve the user ID or use the format 'https://x.com/user/status/tweetId' to find out which user posted the note (by replacing 'user' with the actual username), this approach becomes impractical when I need to retrieve the users for a large volume of tweets.

Is there a more efficient solution to this issue? I'm looking for a way to retrieve the user information for each tweet without having to manually process the URL or search for the user ID. Thanks.

**Comment by jbaxter** [comment]
You could use the paid X API to retrieve this info. It's not part of the Community Notes dataset available for free.

**Comment by Liumucan** [comment]
Thank you for your response. I've noticed that many tweet IDs have been deleted by users. Is it possible to retrieve the user IDs for those deleted tweets using the Twitter API? Thanks.

**Comment by billblake2018** [comment]
This is late and you may already have learned this, but:  If you have a tweet ID, you can use x.com/i/web/status/<ID> to fetch the tweet; you don't need the username.  There's also a mechanism for getting the user given only the user ID, but I'd have to look it up.
