### ISSUE TITLE
Misleading Recent Status Change

### ISSUE THREAD

**Issue by zherebilovgg** [twitter/communitynotes#267]
The description of the variable `timestampMillisOfMostRecentStatusChange` says: "Value is -1 if the note's status has never changed."
Nevertheless, I can see some notes (e.g. noteid 1790437723506921595) for which `timestampMillisOfMostRecentStatusChange = -1` but `firstnonnmrstatus` is not the same as `currentstatus`, suggesting that at some point the status of these notes did change. Is this a bug?

**Comment by jiansongc** [comment]
Thanks for the question.

The feature timestampMillisOfMostRecentStatusChange was added July 2024, it is only not -1 if the note has status change after when the feature was added. 

You can see the code comments here: https://github.com/twitter/communitynotes/blob/50526b6bd50cb0d501246e962a5825d4a33d77e5/sourcecode/scoring/note_status_history.py#L117
