### ISSUE TITLE
Unnable to submit community notes.

### ISSUE THREAD

**Issue by ghost** [twitter/communitynotes#279]
**Describe the bug**
I am unable to submit Community Notes.

**To Reproduce**
1. Go to any post.
2. Click on the "..." button.
3. Click "Write a Community Note".
4. Fill out the form.
5. You should see the error "All fields are required. Please make sure you’ve answered all questions." regardless of which parts of the form are filled out.

**Expected behavior**
The community note is submitted if all fields are filled.

**Screenshots**
![The top of the Community notes form](https://github.com/user-attachments/assets/2365fc24-f9ca-4fd9-9699-888bfe2dc147)
![The actual note](https://github.com/user-attachments/assets/7565bd5a-ce03-4c58-844e-a93f02038564)
![It refuses to submit](https://github.com/user-attachments/assets/f6f16961-9a88-4b3d-8e00-a135454fc766)

**Environment**
The x.com website on Brave Browser (Android) and the x.com website on Firefox (Linux).

**Additional context**
None.

**Comment by BernaLang** [comment]
Also saw this issue. Can't seem to find an explanation but I can't submit any CN at all, it just displays that error

**Comment by jbaxter** [comment]
https://x.com/kcoleman/status/1856056140364427666

Thank you for the reports!
