### ISSUE TITLE
Community notes data is out of date – most recent contribution was 7 days ago

### ISSUE THREAD

**Issue by andylolz** [twitter/communitynotes#288]
Similar issues: #259; #254.

The [download data page](https://x.com/i/communitynotes/download-data) currently says:
> “Data includes contributions up until 1:02 AM · Nov 22, 2024”

**Comment by andylolz** [comment]
It is back up to date again now.

**Comment by plopnl** [comment]
I'm sorry to say that it's stuck again, this time on 31-01-2025

**Comment by plopnl** [comment]
just came back to life.

**Comment by plopnl** [comment]
i don't wanna be a drag but it's stuck on the 14th.

**Comment by plopnl** [comment]
Am i the only 1 who notices (checks) it when the url on the data shows a wrong and old date?
It is stuck on the 11th

**Comment by andylolz** [comment]
> Am i the only 1 who notices (checks) it when the url on the data shows a wrong and old date?

You're not the only one :)

But I appreciate you bumping this ticket when it happens! I'll try to share the burden.

**Comment by andylolz** [comment]
I'm minded to open a new ticket each time this happens, since I think that might more accurately represent the situation. This may well be a different issue (though the symptom is the same). A new issue probably helps provide a better historical record.

**Comment by plopnl** [comment]
As we never get to know the cause the cleanest way would be to rename this thread and remove everything after the -.
That way we avoid cluttering with many kinda the same threads.

> You're not the only one :)

that's a relief

**Comment by jbaxter** [comment]
Thank you! Resolved now, but indeed we appreciate you doing this @plopnl and @andylolz. I don't get notifications for messages on old closed issues, so I'd suggest creating a new issue if this happens again and you'd like to make sure we see (although we also have internal alerting so hopefully it's not necessary for you to flag to us, it certainly doesn't hurt, and it makes me happy that people are actively consuming the data downloads).

**Comment by plopnl** [comment]
Ok next time i'll start a new issue, but i hope @andylolz beats me to it.
