### ISSUE TITLE
The note scoring code is incompatible with the current data file format

### ISSUE THREAD

**Issue by shiruken** [twitter/communitynotes#55]
**Describe the bug**
The published note scoring code is incompatible with the current data file format.

**To Reproduce**
1. Download [source code](https://github.com/twitter/communitynotes/tree/main/static/sourcecode)
2. Download [Birdwatch data files](https://twitter.com/i/communitynotes/download-data)
3. Run `python main.py`
4. Fails assertion while processing user enrollment status data

**Expected behavior**
Program should output scored notes

**Screenshots**

```Python traceback
❯ python main.py
invalid literal for int() with base 10: 'noteId'
invalid literal for int() with base 10: 'noteId'
invalid literal for int() with base 10: 'noteId'
invalid literal for int() with base 10: 'timestampOfLastStateChange'
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    run_scoring()
  File "main.py", line 44, in run_scoring
    _, ratings, noteStatusHistory, userEnrollment = process_data.get_data(
  File "process_data.py", line 32, in get_data
    notes, ratings, noteStatusHistory, userEnrollment = read_from_tsv(
  File "process_data.py", line 122, in read_from_tsv
    assert len(userEnrollment.columns.values) == len(c.userEnrollmentTSVColumns) and all(
AssertionError: userEnrollment columns don't match:
['timestampOfLastEarnOut'] are extra columns,
[] are missing.
```

**Environment**

```zsh
❯ python --version
Python 3.10.9

❯ pip freeze
contourpy==1.0.7
cycler==0.11.0
fonttools==4.38.0
kiwisolver==1.4.4
matplotlib==3.6.2
numpy==1.23.5
packaging==23.0
pandas==1.5.1
Pillow==9.4.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.7.1
six==1.16.0
torch==1.13.0
typing_extensions==4.4.0
```

**Comment by bradmiller** [comment]
HI Shiruken,

Thanks for raising this, and apologies for the outage.  I'll release a fix today.

best,
-Brad

**Comment by bradmiller** [comment]
I think this should be addressed by https://github.com/twitter/communitynotes/pull/56

Please let me know if you continue seeing any issues.

**Comment by shiruken** [comment]
Looks like that resolved it. Thanks!
