### ISSUE TITLE
Can’t sign up on iOS safari

### ISSUE THREAD

**Issue by loodvn** [twitter/communitynotes#83]
Hi there, 

The sign up button (https://mobile.twitter.com/i/communitynotes/about) seems to be hidden below the scrollable area on iOS Safari. In both portrait and landscape orientation. 
Is this intentional?

iPhone SE 16.1.1

**Comment by lucasnantonio** [comment]
Hi! Could you please send us a screenshot?

**Comment by lucasnantonio** [comment]
Hi, checking if this is still an issue. Could you provide a screenshot or an update?
Thanks!

**Comment by loodvn** [comment]
hi Lucas, thanks for following up! Please see the video screenshot below

https://github.com/twitter/communitynotes/assets/13983198/632bf891-ea6d-4756-b064-7b4069cf1ad0

**Comment by elvey** [comment]
FYI, I can’t reproduce this on iOS 16.6 on iPhone XR. I can scroll, and it stays visible in landscape and portrait mode. (it is slightly obscured in the former.) Update and try again? which generation SE?

**Comment by loodvn** [comment]
Just tried now and it works! New phone, iPhone XR 16.6. Slight issue with SMS verification but I’ll figure it out. 

The July video was actually XR 16.latest at the time.
