### ISSUE TITLE
I wasn't notified when a liked tweet was given a community note.

### ISSUE THREAD

**Issue by ffalor** [twitter/communitynotes#86]
**Describe the bug**
We were supposed to get a "heads up" if a tweet we liked, replied to or retweeted gets a community note added to it.
https://twitter.com/CommunityNotes/status/1628158167006994436

I saw the below tweet long before the community note was added to it. I was concerned with how long it was taking for a community note to be added so I liked it to test if people who interacted with the tweet would actually be notified.

You can see my like still there, and I was never notified.

**To Reproduce**
1. Like a tweet before the fact check
2. Tweet gets fact checked

**Expected behavior**
I would expect some form of notification saying a tweet I interreacted with was given a community note.

**Screenshots**
![image](https://user-images.githubusercontent.com/35144141/230521430-c2c3f588-a103-4ac8-a176-df5db11e4701.png)

**Environment**
I've check on both android and web no notification was sent.

**Comment by twitterbirdwatch** [comment]
Thanks for the report and paying close attention. Indeed, we've been ramping these notifications up over time. Been monitoring to ensure they don't overload the system. Should be going to everyone who liked/RTed/replied soon.

**Comment by ffalor** [comment]
Awesome, community notes is the main reason I use twitter for news. Thanks for all the hard work.

**Comment by lucasnantonio** [comment]
We continue to ramp up the notifications here. Still not at 100% but getting there. Will close the issue for now.
