### ISSUE TITLE
List out the appropriate dependencies for users

### ISSUE THREAD

**Issue by dongle-the-gadget** [twitter/communitynotes#87]
**Is your feature request related to a problem? Please describe.**
Currently, there seems to be no documentation on the dependencies required to run the Community Notes program, making it more difficult for normal users to match Twitter's internal environment and causes build errors along the way.

For example, the `constants.py` and `process_data.py` files now uses some numpy objects that are now considered deprecated and throws out errors due to that. Additionally, `process_data.py` assumes that Python will open TSV files using UTF-8, which is true for *nix environments, but not Windows.

**Describe the solution you'd like**
Document the necessary dependencies (along with the versions) to run Community Notes.

**Describe alternatives you've considered**
I've not considered any alternatives.

**Additional context**
No additional context available.

**Comment by twitterbirdwatch** [comment]
Yes the code is expected to work on *nix environments. We'd welcome a documentation PR that explains steps to run it on other platforms.

**Comment by dirkphilip** [comment]
This answer does not fully address the issue raised here.
It would still be helpful to know what versions of Python and the main dependencies are used. Not only to run the code without getting warnings but also for proposing potential improvements to the code.
