### ISSUE TITLE
notes are not shown in case of user not logged in

### ISSUE THREAD

**Issue by laplasz** [twitter/communitynotes#95]
**Describe the bug**
notes are not always shown in case of user not logged in

**To Reproduce**
logout from twitter - visit a tweet which has a note - like this one:
https://twitter.com/POTUS/status/1637136790208356354
but here is another tweet which has 2 notes, and only 1 is shown 
https://twitter.com/elonmusk/status/1651602599345373186

**Expected behavior**
notes should be always visible for everyone for example if tweet was shared with someone who does not have an account or a tweet which was embedded.

**Screenshots**
![Tucker_login](https://user-images.githubusercontent.com/6382898/235263745-24f936ac-942e-4eb7-87a6-17ac8579b715.png)
![Potus_login](https://user-images.githubusercontent.com/6382898/235263762-3d7a8e69-fbfe-4327-8ad1-ae76165154c6.png)
![Tucker_logout](https://user-images.githubusercontent.com/6382898/235263787-53e884e3-b4b4-483f-870f-1d5db67e54fc.png)
![Potus_logout](https://user-images.githubusercontent.com/6382898/235263799-d7a30ddd-b62d-40bc-a1f2-12cda82e26d5.png)

**Environment**
any web browser desktop or mobile

**Comment by twitterbirdwatch** [comment]
Thanks for the report. Just tested. See all the notes when either logged in or logged out. Might be an intermittent issue w/ a cache? If you try again do you see them all?

**Comment by laplasz** [comment]
![IMG_0331](https://user-images.githubusercontent.com/6382898/235288639-ac61b933-38c4-4ee0-be42-f0c324c49d7c.png)
So this one was taken as a screenshot from iphone. Same behaviour.
Maybe it is due the the location? I am in Europe, Hungary..
I started to experience this when I shared a tweet with my friend who was not logged in and could not find the notes. So this behaviour occurs not just for me.

**Comment by twitterbirdwatch** [comment]
Thank you. Now able to reproduce the problem when on VPN through Hungary. We expect it to work for logged out globally. Will investigate.

**Comment by laplasz** [comment]
Any update on this? Thx

**Comment by lucasnantonio** [comment]
Thank you for the reminder! We're taking another look but couldn't find the cause yet.

**Comment by lucasnantonio** [comment]
Hi @laplasz , we believe the issue is now resolved. Could you please test again and let us know if you can reproduce it?

**Comment by laplasz** [comment]
Hi There! - yes - now twitter is showing community notes even for readers who does not have an account or not logged in.
Thanks for the great work!
